# Generated by Django 4.2 on 2023-04-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_attachment_options_alter_film_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
